apps/users/urls.py
"""Circles URLs."""

# Django
from django.urls import path

# Views
from .views.users import LoginView,LogoutView,IndexView,SignUpView,ActivateAccount,EmailConfirmView

urlpatterns = [
    path('',LoginView.as_view(),name="login"),
    path('users/logout',LogoutView.as_view(),name="logout"),
    path('users/index',IndexView.as_view(),name="index"),
    path('users/signup',SignUpView.as_view(),name="signup"),
    path('users/email_confirm',EmailConfirmView.as_view(),name="email_confirm"),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
]

conf/urls.py
"""Core URLs."""
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.users.urls', 'users'), namespace='users')),
    path('', include(('apps.game_core.urls', 'game_core'), namespace='game_core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models/users.py
"""Users models."""

# Django
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import admin
from django.contrib.auth.models import AbstractUser


# Utilities
from apps.utils.models import HistoryModel


class User(HistoryModel, AbstractUser):
	"""User model.
	Extend from Django's Abstract User, change the username field
	to email and add some extra fields.
	"""
	customer_id = models.CharField(max_length=100, blank=True,null=True)
	email = models.EmailField(
		'email address',
		unique=True,
		error_messages={
			'unique': 'A user with that email already exists.'
		}
	)
	# phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

	email_confirmed = models.BooleanField(
		'verified',
		default=False,
		help_text='Set to true when the user have verified its email address.'
	)

	def __str__(self):
		"""Return username."""
		return self.username

	def get_short_name(self):
		"""Return username."""
		return self.username

	@property
	def description(self):
		"""Return username."""
		return 'Descripcion para el usuario {}'.format(self.username)
        
admin.site.register(User)

apps/users/forms.py
from django import forms
from django.conf import settings
User = settings.AUTH_USER_MODEL
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


# Sign Up Form
class SignUpForm(UserCreationForm):
	class Meta:
		fields = ('email','password1','password2')
		model = get_user_model()
		
	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		# self.fields['username'].label = 'Usuario'
		self.fields['email'].label = 'Correo electrónico'
		for fieldname in ['email', 'password1', 'password2']:
			self.fields[fieldname].help_text = None

		

apps/users/views/users.py
""" User's Views """

# Django 
from django.contrib.auth import authenticate,logout,login
from django.views.generic import View,ListView,UpdateView,CreateView,DeleteView,DetailView
from django.views.generic.base import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes,force_text
from django.contrib import messages

from django.http import FileResponse
from django.conf import settings
from django.contrib.auth import get_user_model

# For Email conf
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from conf.settings import EMAIL_HOST_USER

# Forms
from ..forms import SignUpForm
# Utils

from apps.utils.tokens import account_activation_token

# Models
User = get_user_model()


class LoginView(View):
	def post(self, request):
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)

			else:
				return HttpResponse("Inactive user.")
		else:
			return HttpResponseRedirect(settings.LOGIN_URL)

		return render(request, "index.html")
	def get(self, request, **kwargs):     
		print(request)
		return render(request, 'login.html')


class LogoutView(View):
	def get(self, request):
		logout(request)
		return HttpResponseRedirect(settings.LOGIN_URL)


class IndexView(TemplateView):
	template_name = 'index.html'
	paginate_by = 5
	no_of_message = 1
			
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = User.objects.get(pk=self.request.user.pk)

		context.update({
			'user': user,
		})
		
		return context

        
class SignUpView(CreateView):
	form_class = SignUpForm
	template_name = 'signup.html'
	
	def get(self, request, *args, **kwargs):
		form = self.form_class()
		return render(request, self.template_name, {'form': form})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			user.is_active = False # Deactivate account till it is confirmed
			user.username = user.email # Deactivate account till it is confirmed
			user.save()

			try:
				"""Send account verification link"""
				current_site = get_current_site(request)
				subject = 'Hi {}, please verify your account'.format(user.email)
				from_email = 'TicTacBomb <noreply@tictacbomb.com>'
				text_content = 'TicTacBomb <noreply@tictacbomb.com>'
				message = render_to_string('account_activation_email.html', {
					'user': user,
					'domain': current_site.domain,
					'uid': urlsafe_base64_encode(force_bytes(user.pk)),
					'token': account_activation_token.make_token(user),
				})
				msg = EmailMessage(subject, message, from_email, [user.email])
				msg.content_subtype = 'html'
				msg.send()
			except Exception as e:
				print('error',e)
			return HttpResponseRedirect(reverse('users:email_confirm'))


		return render(request, self.template_name, {'form': form})


class ActivateAccount(View):
	def get(self, request, uidb64, token, *args, **kwargs):
		try:
			uid = force_text(urlsafe_base64_decode(uidb64))
			user = User.objects.get(pk=uid)
		except (TypeError, ValueError, OverflowError, User.DoesNotExist):
			user = None

		if user is not None and account_activation_token.check_token(user, token):
			user.is_active = True
			user.email_confirmed = True
			user.save()
			login(request, user)
			messages.success(request, ('Your account have been confirmed.'))
			return HttpResponseRedirect(reverse('users:index'))
		else:
			messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
			return HttpResponseRedirect(reverse('users:login'))


class EmailConfirmView(TemplateView):
	def get(self, request, **kwargs):     
		return render(request, 'email_confirm.html')

	

apps/users/templates/account_activation_email.html
{% load static %}
{% autoescape off %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Actionable emails e.g. reset password</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="content-wrap">
                            <table  cellpadding="0" cellspacing="0">
                                <tr>
                                    <td>
                                        LA CARTA
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <h3>Hola {{ user.username }},</h3>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                    Click on link to confirm your email!
                                    </td>
                                </tr>
                                
                                <tr>
                                    http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

                                </tr>
                              </table>
                        </td>
                    </tr>
                </table>
                <div class="footer">
                    <table width="100%">
                        <tr>
                            <td class="aligncenter content-block">Follow <a href="#">@TicTacToe</a> on Twitter.</td>
                        </tr>
                    </table>
                </div></div>
        </td>
        <td></td>
    </tr>
</table>

</body>
</html>
{% endautoescape %}

apps/users/templates/email_confirm.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>email confirm</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body class="gray-bg">
    <div class="middle-box text-center animated fadeInDown">
        <h2 class="font-bold">Te hemos enviado un correo para verificar la cuenta.</h2>
    </div>
</body>
</html>

apps/users/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row m-b-lg m-t-lg">
        <div class="col-md-6">
            <div class="profile-image">
				<img src="{% static 'img/user.png' %}" class="img-circle circle-border m-b-md" alt="profile">
            </div>
            <div class="profile-info">
                <div class="">
                    <div>
                        <h2 class="no-margins">
                            {{request.user}}
                        </h2>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <h3>Personal Info {{object_list}}</h3>
                    <p class="small">
                        <label>Email</label>
                        <p>{{user}}</p>
                        <p>{{user.last_name}}</p>
                        <button class="btn btn-primary btn-block">Edit Info</button>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

apps/users/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Login</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="icon" type="image/png" href="images/icons/favicon.ico" />


<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body style="background-color: #666666;">
<div class="limiter">
<div class="container-login100">
<div class="wrap-login100">
<form class="login100-form validate-form" method="POST">
    {% csrf_token %}
<span class="login100-form-title p-b-43">
Inicia sesión
</span>
<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
<input class="input100" type="text" name="username">
<span class="focus-input100"></span>
<span class="label-input100">Email</span>
</div>
<div class="wrap-input100 validate-input" data-validate="Password is required">
<input class="input100" type="password" name="password">
<span class="focus-input100"></span>
<span class="label-input100">Password</span>
</div>

<div class="container-login100-form-btn">
<button type="submit" class="login100-form-btn">Login</button>
</a>
</div>

<div class="container-login100-form-btn">
    <a href="{% url 'users:signup' %}">Registrarse</a>
</div>




</form>
<div class="login100-more" style="background-image: url('/static/img/bg-01.jpg');">
</div>
</div>
</div>
</div>

<script src="{% static 'js/main.js' %}" type="933b86ff20d9d149d7f0e96f-text/javascript"></script>
</html>

apps/users/templates/signup.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>LaCarta</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">LaCarta</h1>

            </div>
            <h3>Registrarse en LaCarta</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form | crispy }}

                <button class="btn btn-primary btn-block" type="submit">Login</button>
            </form>
        </div>
    </div>

 
</body>
    