apps/game_core/urls.py
"""Circles URLs."""

# Django
from django.urls import path

# Views
from .views.game_core import GameRoomView,ScoreView

urlpatterns = [
    path('game/game-room',GameRoomView.as_view(),name="game_room"),
    path('game/score',ScoreView.as_view(),name="score"),
]

apps/users/urls.py
"""Circles URLs."""

# Django
from django.urls import path

# Views
from .views.users import LoginView,LogoutView,IndexView,SignUpView,ActivateAccount,EmailConfirmView

urlpatterns = [
    path('',LoginView.as_view(),name="login"),
    path('users/logout',LogoutView.as_view(),name="logout"),
    path('users/index',IndexView.as_view(),name="index"),
    path('users/signup',SignUpView.as_view(),name="signup"),
    path('users/email_confirm',EmailConfirmView.as_view(),name="email_confirm"),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
]

conf/urls.py
"""Core URLs."""
# Django
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.users.urls', 'users'), namespace='users')),
    path('', include(('apps.game_core.urls', 'game_core'), namespace='game_core')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load auth_extras %}

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Tic Tac Toe</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="image/x-icon">  


</head>

<body>

<div id="wrapper">

    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">{{request.user}}</strong>
                             {% comment %} </span> <span class="text-muted text-xs block">General Manager<b class="caret"></b></span> </span> </a> {% endcomment %}
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a href="{% url 'users:logout' %}">Logout</a></li>
                            </ul>
                    </div>
                    <div class="logo-element">
                        TTT
                    </div>
                </li>
                

                <li>
                    <a href="{% url 'game_core:game_room' %}"><i class="fa fa-play"></i> <span class="nav-label">Game room</span> </a>
                </li>
                <li>
                    <a href="{% url 'game_core:score' %}"><i class="fa fa-flag"></i> <span class="nav-label">My Score</span> </a>
                </li>
                <li>
                    <a href="{% url 'users:index' %}"><i class="fa fa-user"></i> <span class="nav-label">Profile</span> </a>
                </li>
                <li class="landing_link">
                  <a href="{% url 'users:index' %}">
                        
                        <span class="nav-label">Name: Cris Arias</span><br>
                        <span class="nav-label">Mail: ariasover@gmail.com</span><br>
                        <span class="nav-label">Phone: +50496068888</span>
                    
                    </a>
                </li>
                
            
            </ul>

        </div>
    </nav>

    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                    <!-- <form role="search" class="navbar-form-custom" method="post" action="#">
                        <div class="form-group">
                            <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form> -->
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="{% url 'users:logout' %}">
                            <i class="fa fa-sign-out"></i> Cerrar sesión
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <div class="wrapper wrapper-content">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <div class="footer">
           
            <div>
                <strong>Copyright</strong> TicTacToe &copy; 2020
            </div>
        </div>

    </div>
</div>

<!-- Mainly scripts -->
<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'js/inspinia.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>

{% if messages %}
    {% for message in messages %}
        {% comment %} {% if message.tags == "alert alert-danger" %} {% endcomment %}
            swal({
                title: "{{message}}",
                text: "",
                icon: "{{message.extra_tags}}",
                button: "Cerrar",
            });
        {% comment %} {% endif %} {% endcomment %}

    {% endfor %}
{% endif %}

</script>
</body>

</html>

templates/configuration.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Configuración 
                </h1>
               
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Speech</h5>
                </div>
                <div class="ibox-content">
                    <a href="{% url 'speech:list' %}" class="btn btn-primary btn-block m-t"><i class="fa fa-file-text-o"></i> Ver configuración</a>
                </div>
                    
            </div>            
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Usuarios</h5>
                </div>
                <div class="ibox-content">
                    <a href="{% url 'users:users_list' %}" class="btn btn-primary btn-block m-t"><i class="fa fa-file-text-o"></i> Ver configuración</a>
                </div>
                    
            </div>            
        </div>
        <div class="col-lg-4">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Permisos</h5>
                </div>
                <div class="ibox-content">
                    <a href="{% url 'users:groups_list' %}" class="btn btn-primary btn-block m-t"><i class="fa fa-file-text-o"></i> Ver configuración</a>
                </div>
                    
            </div>            
        </div>
        
    </div>
    
{% endblock %}

templates/confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Delete confirmation</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">

    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body class="gray-bg">
    <div class="middle-box text-center animated fadeInDown">
        <form method="post">{% csrf_token %} 
            <h2 class="font-bold">¿Desea eliminar el registro?</h2>
            <input class="btn btn-sm btn-primary m-t-n-xs" type="submit" value="Confirmar"> 
            {% comment %} <a class="btn btn-sm btn-danger m-t-n-xs" type="submit" value="Cancelar"> {% endcomment %}
            <a href="{{ view.get_success_url }}" class="btn btn-sm btn-danger m-t-n-xs">Cancelar</a> 
        </form> 
    </div>
</body>
</html>

templates/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

templates/search.html
<form method="get">
<div class="row m-b-sm m-t-sm">
    <div class="col-md-12">
        <div class="input-group">
            {% for field in filter.form %}
                {{ field.errors }}
                {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            {% endfor %}
            {% comment %} <input type="text" placeholder="Search" class="input-sm form-control">  {% endcomment %}
            <span class="input-group-btn">
                <button type="button" class="btn btn-sm btn-primary"> Buscar</button> 
            </span>
        </div>
    </div>
</div>
</form>